## PRODUTOS


tabpreco <- dbGetQuery(con2,"SELECT * FROM TABPRECO WHERE TBPSITUACAO='A' AND 
                       (TBPDTVALIDADE >='TODAY' OR TBPDTVALIDADE IS NULL)")

View(tabpreco)


tbpprodu2 <- dbGetQuery(con2,"SELECT TBPCODIGO,P.PROCODIGO,PRODESCRICAO,PROSITUACAO 
                              FROM TBPPRODU P
                               LEFT JOIN (SELECT PROCODIGO,PRODESCRICAO,PROSITUACAO FROM PRODU)A ON A.PROCODIGO=P.PROCODIGO
                     WHERE TBPCODIGO IN (102)")

View(tbpprodu)


tbpprodu3 <- dbGetQuery(con2,"SELECT TBPCODIGO,P.PROCODIGO,PRODESCRICAO,PROSITUACAO 
                              FROM TBPPRODU P
                               LEFT JOIN (SELECT PROCODIGO,PRODESCRICAO,PROSITUACAO FROM PRODU)A ON A.PROCODIGO=P.PROCODIGO
                     WHERE TBPCODIGO IN (103)")

View(tbpprodu)


tbpprodu4 <- dbGetQuery(con2,"SELECT TBPCODIGO,P.PROCODIGO,PRODESCRICAO,PROSITUACAO 
                              FROM TBPPRODU P
                               LEFT JOIN (SELECT PROCODIGO,PRODESCRICAO,PROSITUACAO FROM PRODU)A ON A.PROCODIGO=P.PROCODIGO
                     WHERE TBPCODIGO IN (104)")

View(tbpprodu)


tbpprodu5 <- dbGetQuery(con2,"SELECT TBPCODIGO,P.PROCODIGO,PRODESCRICAO,PROSITUACAO 
                              FROM TBPPRODU P
                               LEFT JOIN (SELECT PROCODIGO,PRODESCRICAO,PROSITUACAO FROM PRODU)A ON A.PROCODIGO=P.PROCODIGO
                     WHERE TBPCODIGO IN (105)")

View(tbpprodu)


tbpprodu6 <- dbGetQuery(con2,"SELECT TBPCODIGO,P.PROCODIGO,PRODESCRICAO,PROSITUACAO 
                              FROM TBPPRODU P
                               LEFT JOIN (SELECT PROCODIGO,PRODESCRICAO,PROSITUACAO FROM PRODU)A ON A.PROCODIGO=P.PROCODIGO
                     WHERE TBPCODIGO IN (201)")

View(tbpprodu6)


tbpprodu7 <- dbGetQuery(con2,"SELECT TBPCODIGO,P.PROCODIGO,PRODESCRICAO,PROSITUACAO 
                              FROM TBPPRODU P
                               LEFT JOIN (SELECT PROCODIGO,PRODESCRICAO,PROSITUACAO FROM PRODU)A ON A.PROCODIGO=P.PROCODIGO
                     WHERE TBPCODIGO IN (202)")

View(tbpprodu7)

## EYEZEN

tbpprodu8 <- dbGetQuery(con2,"SELECT TBPCODIGO,P.PROCODIGO,PRODESCRICAO,PROSITUACAO 
                              FROM TBPPRODU P
                               LEFT JOIN (SELECT PROCODIGO,PRODESCRICAO,PROSITUACAO FROM PRODU)A ON A.PROCODIGO=P.PROCODIGO
                     WHERE TBPCODIGO IN (309)")

View(tbpprodu8)


## KODAK VS

tbpprodu9 <- dbGetQuery(con2,"

WITH PROD AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE (PRODESCRICAO LIKE '%KODAK%' AND
PRODESCRICAO NOT LIKE '%SINGLE%') AND GR2CODIGO=3
 AND PROSITUACAO='A'),
 
TAB_ACORDO AS (SELECT TBPCODIGO,TBPDESCRICAO FROM TABPRECO WHERE TBPSITUACAO='A' AND 
                       (TBPDTVALIDADE >='TODAY' OR TBPDTVALIDADE IS NULL) AND TBPCODIGO<>202 AND
                        TBPTABCOMB='N')

SELECT P.TBPCODIGO,P.PROCODIGO,PRODESCRICAO,TBPPCDESCTO,TBPPCOVENDA2,TBPPCDESCTO2,TBPPCOVENDA2
                              FROM TBPPRODU P
                               INNER JOIN PROD PR ON PR.PROCODIGO=P.PROCODIGO
                                INNER JOIN TAB_ACORDO TA ON P.TBPCODIGO=TA.TBPCODIGO
")

View(tbpprodu9)


dbGetQuery(con2,"SELECT PROCODIGO FROM PRODU WHERE PROCODIGO2='LA0199'")

## CRIZAL LA

tbpprodu10 <- dbGetQuery(con2,"

WITH PROD AS (SELECT PROCODIGO2 FROM PRODU WHERE PRODESCRICAO LIKE '%CRIZAL%' AND
LEFT(PROCODIGO2,2)='LA' AND PROSITUACAO='A'),
 
TAB_ACORDO AS (SELECT TBPCODIGO,TBPDESCRICAO FROM TABPRECO WHERE TBPSITUACAO='A' AND 
                       (TBPDTVALIDADE >='TODAY' OR TBPDTVALIDADE IS NULL) AND
                        TBPTABCOMB='N')

SELECT DISTINCT P.TBPCODIGO,
                  P.PROCODIGO,
                    TBPPCDESCTO,
                     TBPPCOVENDA2,
                       TBPPCDESCTO2,
                         TBPPCOVENDA2
                              FROM TBPPRODU P
                               INNER JOIN PROD PR ON PR.PROCODIGO2=P.PROCODIGO
                                INNER JOIN TAB_ACORDO TA ON P.TBPCODIGO=TA.TBPCODIGO")

View(tbpprodu10)

prod <-
  dbGetQuery(con2,"SELECT DISTINCT PROCODIGO,PRODESCRICAO FROM PRODU WHERE PROCODIGO2 IS NULL AND PROSITUACAO='A'")


left_join(tbpprodu10,prod,by="PROCODIGO") %>% View()

## STELLEST=================
  
tbpprodu11 <- dbGetQuery(con2,"

WITH PROD AS (SELECT PROCODIGO FROM PRODU WHERE PRODESCRICAO LIKE '%STELLEST%' AND PROSITUACAO='A'),
 
TAB_ACORDO AS (SELECT TBPCODIGO,TBPDESCRICAO FROM TABPRECO WHERE TBPSITUACAO='A' AND 
                       (TBPDTVALIDADE >='TODAY' OR TBPDTVALIDADE IS NULL) AND
                        TBPTABCOMB='N')

SELECT DISTINCT P.TBPCODIGO,
                  P.PROCODIGO,
                    TBPPCDESCTO,
                     TBPPCOVENDA2,
                       TBPPCDESCTO2,
                         TBPPCOVENDA2
                              FROM TBPPRODU P
                               INNER JOIN PROD PR ON PR.PROCODIGO=P.PROCODIGO
                                INNER JOIN TAB_ACORDO TA ON P.TBPCODIGO=TA.TBPCODIGO")

View(tbpprodu11)  



## ================


dbGetQuery(con2,"SELECT PROCODIGO FROM PRODU WHERE PROCODIGO2='LA0209'")


aux <- read.table(text = read_clip(), header = TRUE, sep = "\t") 
